### ISSUE TITLE
Add Outnumbered: Determine which Side is Outnumbered

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#19]
Which Side is Outnumbered?

- This takes place Just before initiative is rolled
- The system calculates how many Friendly and how many Hostile tokens are in the combat.
- Whichever side has fewer combatants is “Outnumbered”
- The Outnumbered side will **win initiative** in case of ties.
- The Outnumbered side will be indicated to the GM visually
- If both sides are the same, the Hostiles win in the event of ties.

QUESTIONS
- How does the system determine who is the Hostile side? 
- Should the system present a selector for the GM to determine who is Hostile when it's a tie?

**Comment by LeRatierBretonnien** [comment]
To determine Hostile/Friendly, I will make use of the token disposition : 
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/1085008/7f8d9f94-934e-42e5-85e1-7ebde4a4a207)

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
