### ISSUE TITLE
Update Character Sheet Displays: Add attribute for Initiative Modifier

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#20]

**Comment by LeRatierBretonnien** [comment]
Add also initiative/surprise bonus to monster sheets

**Comment by ArcanistWill** [comment]
@LeRatierBretonnien Is this where the sheet has been updated?
![image](https://github.com/user-attachments/assets/01c44367-460c-45b2-9870-f00eb5952a64)

**Comment by ArcanistWill** [comment]
@Archon-Autarch If the initial attributes roll shows an Initiative bonus or penalty, is the Tweak supposed to be added to that to generate the final Initiative Bonus? See previous screenshots I attached.

**Comment by LeRatierBretonnien** [comment]
In fact, I forgot about this "tweak" window. So it is up to you to choose which one we keep
1 - We keep the new "Initiative bonus", and I drop the field in the Tweak window
2 - We keep the Tweak window, then I remove the new field I added , and I use the Tweak value in the Combat Tracker. 

Tell me

**Comment by ArcanistWill** [comment]
For the Initiative Bonus, I want to ask @Archon-Autarch to confirm if he agrees with what I recommend, which is:

1. Keep the calculated and displayed Initiative Bonus (screenshot 1)
2. Keep the tweaks window function that will allow entering a "delta" Initiative Bonus (screenshot 2)
3. (new) Calculate the final Initiative Bonus as the sum of the rolled bonus plus the tweak value entered.
4. (new) Display the calculated final Initiative Bonus on the Abilities page (screenshot 3).
Note that right now, I think the Abilities page displays only the Tweak value which looks like it overrides the calculated bonus?

That's my thought. Please confirm if this makes sense.

**Comment by LeRatierBretonnien** [comment]
OK, nor problem, let's wait confirmation from Archon-Autarch

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
