### ISSUE TITLE
Support Foundryv12 changes

### ISSUE THREAD

**Issue by LeRatierBretonnien** [AutarchLLC/foundryvtt-acks-core#26]
Fix migration bugs and warnings

**Comment by ArcanistWill** [comment]
@LeRatierBretonnien There are still a few deprecated warnings when running in Foundry 12. Are you planning to fix? This is when running from the latest code in the Initiative branch.
![image](https://github.com/user-attachments/assets/ef8a71d6-60d6-46fd-91e5-f286846baf02)
![image](https://github.com/user-attachments/assets/eafb18e6-8acb-409a-a450-bc99cc786020)

**Comment by LeRatierBretonnien** [comment]
The first one is 100%  related to TheForge, not ACKS, so contact TheForge team for that.

The second is due to to fact that the system is still v11/v12 compatible. If you want only v12 support, then the warning will be removed.

**Comment by ArcanistWill** [comment]
> The first one is 100% related to TheForge, not ACKS, so contact TheForge team for that.
> 
> The second is due to to fact that the system is still v11/v12 compatible. If you want only v12 support, then the warning will be removed.

OK, thank you, then I agree these can be closed. We can update the warnings much later when version 14 is the current standard.
