### ISSUE TITLE
Character generator is not saving results into Character Sheet

### ISSUE THREAD

**Issue by thetwoface** [AutarchLLC/foundryvtt-acks-core#29]
**Describe the bug**
When you create new Character Actor there is an option to use Character Generator to generate attributes and starting gold. Character Generator works but does not save result into Character Sheet.

**To Reproduce**
1. Create new Character Actor
2. Make sure all attributes are 0 so Generate Scores button is visible
3. Click Generate Scores button and generate all stats and click Save Changes
4. Look on Character Sheet - all attributes are still 0. Chat card correctly shows generated stats though.

**Expected behavior**
Character sheet is populated using results from Character Generator

**Screenshots**
![CharGenBug](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/305768/fa5e8498-32cb-4425-90d9-34ef05c9c734)

**Additional context**
Foundry VTT version: 12.328
ACKS module version: foundryvtt-acks-core (initiative branch, commit [3595242](https://github.com/AutarchLLC/foundryvtt-acks-core/commit/35952422acb8d00dd8bde47ec01473d8e1079d8c))

**Comment by LeRatierBretonnien** [comment]
Fixed in next release, thanks for the report

**Comment by LeRatierBretonnien** [comment]
(Fixed in 'initiative' branch)
