### ISSUE TITLE
Game World fails to launch after update to game system.

### ISSUE THREAD

**Issue by dasBarkman** [AutarchLLC/foundryvtt-acks-core#31]
Game World fails to launch after module update.
Error returned - Metadata validation failed for system "acks": The file "lib/colorsettings/colorSetting.js" included by system acks does not exist

**To Reproduce**
1. Install/Update Module
2. Start/Create Game world
3. System appears to hang.
4. See error.   Metadata validation failed for system "acks": The file "lib/colorsettings/colorSetting.js" included by system acks does not exist
5. 

**Expected behavior**
After update game world should successfully launch.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 - latest patch
 - Edge
 - I tested on V12 of Foundry - other reports on v11 in ACKS Discord. 

**Additional context**

**Comment by LeRatierBretonnien** [comment]
Oops, 
New release, with all latest fixes : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/download/12.0.11/system.json
