### ISSUE TITLE
unable to add item/weapon to Monster Actor

### ISSUE THREAD

**Issue by dasBarkman** [AutarchLLC/foundryvtt-acks-core#32]
When adding a new item/ability to a monster actor, clicking ok triggers an error. 

**To Reproduce**
1. click on Actor tab
2. Create/open a Monster actor
3. click the plus button to add an item/ability
4. Provide name, click ok.
5. Error appears 

**Expected behavior**
Item/weapon/ability should appear on monster entry.

**Screenshots**
![image](https://github.com/user-attachments/assets/72e294b6-eb16-4169-a0a4-746f169ccd9b)
 
**Desktop (please complete the following information):**
 - OS: Windows 10, latest version
 - Browser Edge
 - Version Latest version 
 - 

**Additional context**

**Comment by LeRatierBretonnien** [comment]
Fixed, new release available : https://github.com/AutarchLLC/foundryvtt-acks-core/releases/download/12.0.12/system.json

**Comment by ArcanistWill** [comment]
Verified that the reported error no longer happens. I think this issue can be closed.
