### ISSUE TITLE
ACKS II Initiative: Ending combat did not clear "Overnumbering" condition.

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#33]
**New Bug**
One time out of perhaps 10 times, when ending combat, the Overnumbering condition persisted on the hostile (monster) side. Not sure how to reproduce.

![overnumbering-notcleared](https://github.com/user-attachments/assets/9b7dec9b-8852-46e0-b197-2f3d0c5e0e01)

**Comment by LeRatierBretonnien** [comment]
Fixed with #37 and #34 fixes.

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
