### ISSUE TITLE
ACKS II Initiative: Changing the use of "Overnumbered" to "Outnumbering"

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#34]
**Modify OverNumbering**

1. Correction - The use of "OverNumbered" was confusing as a name for the condition. This isn't the most obvious in English. Can we instead use "Outnumbering" - which will show that the side is outnumbering the smaller side?
2. Improvement - Is it possible NOT to display the "plus" sign on the map for the side that is Outnumbering the other side?
3. Improvement - Is it possible NOT to display the popup text of "+Outnumbering" and "-Outnumbering" that appears when the condition is applied and removed? 

The reason for comments 2 and 3 above is because it was distracting to the GM. That condition would still be shown on the Combat tracker but not on the map itself, if possible.

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LeRatierBretonnien** [comment]
So this is a change request.

**Comment by LeRatierBretonnien** [comment]
Change ongoing, the "Outnumbering" status is no more display on the token, and icon has been changed.
![image](https://github.com/user-attachments/assets/092fa837-99b5-40be-a64e-e4a28b33d1f7)

**Comment by ArcanistWill** [comment]
> So this is a change request.

Ok, that's fine, let's leave this to the side for now. I can edit the term myself later, to change it to Outnumbering, and we don't have to deal with the other changes then.

**Comment by LeRatierBretonnien** [comment]
I already started to work on it , as it is related also to #37 . Not a big deal anyway.

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
