### ISSUE TITLE
ACKS II Initiative: Incorrect condition for "Casting"

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#35]
**Describe the bug**
When clicking the "Casting" icon, this triggers a "Done" message and sets the Done icon. This should instead be the Casting condition.

**Comment by LeRatierBretonnien** [comment]
Fixed in initiative branch

**Comment by ArcanistWill** [comment]
@LeRatierBretonnien @Archon-Autarch 

Are we expecting the "Casting" condition to show icon on the map token? It is not showing an icon for that condition. See screenshot.

![image](https://github.com/user-attachments/assets/daf2748a-2970-41e1-93fd-eb3be2099346)

**Comment by LeRatierBretonnien** [comment]
Yes, this is normal. This "status" is only visible in the Combat Tracker. 
Icon can be added if needed.

**Comment by ArcanistWill** [comment]
After our Discord chat on 08/24/2024, we agreed this is not a problem and this issue can be closed. No changes needed.
