### ISSUE TITLE
ACKS II Initiative: Monster Invisibility should not show Surprise rolls

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#36]
**Describe the bug**
When monster tokens are set to Invisible before starting combat, their Surprise rolls **should not** be shown. They should be private GM rolls. Instead they are showing up in the chat log.

**To Reproduce**
1. Set monster token visibility to Invisible.
2. Add everyone to combat and start combat
3. The monsters are correctly show Invisible in the tracker but the chat log still shows their result (i.e. Giant Ant is not surprised) - this is not desirable. It should be a private roll if Invisible.

**Comment by LeRatierBretonnien** [comment]
Fixed in initiative branch

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
