### ISSUE TITLE
ACKS II Initiative: Incorrect ordering

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#37]
**Describe the bug**
When one side outnumbers the other, we noticed the initiative wasn't being calculated as intended.

1. Example 1:
We had 6 bandits and (only) 5 PCs in the combat.
Compared to a total of 6 bandits and 9 PCs on the playing area (some PCs not in combat).
The bandits are flagged as "Overnumbering" (e.g. the larger group), which was correct.
BUT in the actual initiative sorting, the bandits are going first, as if the PCs overnumbered them. This is incorrect. The PCs are outnumbered and should go first.
![test1](https://github.com/user-attachments/assets/3bc15ebb-bdcf-4346-b544-ee7fa0f6150b)

2. Example 2:
6 bandits and 5 PCs in combat (This time no other PCs on the playing area).
The bandits are flagged as "Overnumbering" (e.g. the larger group)
BUT again they are going first which is incorrect.
![test2](https://github.com/user-attachments/assets/39c61e4b-39aa-4db9-afac-b4b2d167c274)

3. Example 3: 
Where monsters outnumber PCs, instances of tie (at the same initiative level) the tie is still going to monsters but should be to the outnumbered side.
Second example of this:
![test2a](https://github.com/user-attachments/assets/c9b5acf4-07e0-48ec-b28a-bb551581eb21)

4. Example 4:
In case of tie in size (both groups the same number of combatants), the initiative is supposed to go to the monsters. Right now, it's just sorting alphabetically instead.
Suggested fix for this is that in case of tie, the PCs are assigned the Outnumbering condition. It is as if they outnumber the monsters.

**Comment by LeRatierBretonnien** [comment]
Fixed in initiative head, the issue was v11/v12 compat management.

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
