### ISSUE TITLE
ACKS II Initiative: Initiative Bonus not being used?

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#38]
**Describe the bug**
It appears that the Initiative Bonus is not being used when rolling for initiative. It shows up on the character sheet (or monster sheet) but the rolls always show 1d6+0.

![image](https://github.com/user-attachments/assets/f2a6fcb7-4c7c-4899-859a-f55fad2ac011)

**To Reproduce**
1. Use the Tweaks to assign a specific value to the Initiative Bonus. This is displayed on the character sheet.
2. Roll initiative in the combat tracker.
3. Observe the rolls. It seems not to be including the bonus. There should be an addition of the bonus. The range of values for Initiative is +10 to -10 as per:
"The Judge begins calling out the initiative numbers starting with 10, then 9, then 8, and so on. Each combatant takes his initiative segment when his initiative number is called. The initiative count continues until characters have acted or until it reaches -10, at which point the initiative count ends."

**Comment by LeRatierBretonnien** [comment]
Fixed/modified.
The "initiative bonus" field is showing the initiative bonus from the DEX + the initiative modifier from the tweak
![image](https://github.com/user-attachments/assets/449c4bd3-f1c6-490a-972c-28aea7630482)

Total modifier is then taken into account in init formula

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
