### ISSUE TITLE
ACKS II Initiative: Toggle Delayed / Ready needs to clear Done?

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#39]
**Describe the bug**
When switching conditions between Delayed / Ready / Done, there is a hole. It's possible to end up in both Delayed or Ready and Done.
I think it works correctly to reset Delay / Ready if you click Done. But then you can still click either of the other 2 and it doesn't clear Done. I think this is an error.

![image](https://github.com/user-attachments/assets/171aca21-54b5-4c3a-90a7-9512aecc89ae)

Also, if you End Combat with those conditions still active, those conditions persist. Should they instead be cleared once combat ends?  I think this is an error because I don't know of a scenario where it would make sense to allow the conditions to persist. What do you think?

![image](https://github.com/user-attachments/assets/4e896718-65df-4214-8bb9-b11871c4dbea)

**Comment by ArcanistWill** [comment]
- delay should go away when you advance to the next round, click Done or Ready, or end combat
- ready should go away when you click Done or end combat; it should NOT go away when you advance the round (it lingers round to round)
- should not be able to click both Delay + Done, Ready + Done, or Delay + Ready at same time

**Comment by LeRatierBretonnien** [comment]
- delay should go away when you advance to the next round, click Done or Ready, or end combat -> OK.
- ready should go away when you click Done or end combat; it should NOT go away when you advance the round -> OK
- should not be able to click both Delay + Done, Ready + Done, or Delay + Ready at same time -> OK, check and informations messages has been added.
- Cleanup of all status at end of combat has been checked and fixed also
