### ISSUE TITLE
v12 - Loyalty rolls use modifier for Morale instead of Loyalty

### ISSUE THREAD

**Issue by wyatt-kinkade** [AutarchLLC/foundryvtt-acks-core#42]
**Describe the bug**
Loyalty rolls use modifier for Morale instead of Loyalty

**To Reproduce**
Open the character sheet of a retainer, click on the tooltip to roll loyalty

**Expected behavior**
When the tooltip to roll for retainer loyalty is clicked that it will use the modifier for Loyalty instead of Morale

**Screenshots**
![image](https://github.com/user-attachments/assets/fabeb53b-1e11-4e7e-b95b-7a603b609e99)

**Desktop (please complete the following information):**
 - OS: Windows 10 /Debian 12
 - Browser Firefox/Brave
 - ACKS Module Version 12.0.14
 - Foundry Version 12 330

**Comment by LeRatierBretonnien** [comment]
Note that the dev branch is the 'initiative' branch, not the 'master'.
