### ISSUE TITLE
Regression: Developer console shows chat-related errors

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#5]
**Regression**
Developer console shows errors at first login.

**Environment**
This appeared in the console log of the game world that I have been doing a very limited testing with 1 actor.
Approx 4 days ago was the last time I loaded the world.
This appears at login as Gamemaster without needing to take any further actions.

**Screenshots**
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/70f5f943-3b57-41a9-8a57-b99c92951997)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 122.0.6261.129 (Official Build) (64-bit)

**Comment by LeRatierBretonnien** [comment]
FYI, they are warnings, not errors

**Comment by ArcanistWill** [comment]
This is not an error. It was due to a misconfiguration of my server. Closing. No change needed.
