### ISSUE TITLE
Saving Throw Ordering on Monster Sheets not matching Revised Rulebook and Character Sheets

### ISSUE THREAD

**Issue by wyatt-kinkade** [AutarchLLC/foundryvtt-acks-core#53]
Title says it all, the values along the side are part of an unnumbered list, they merely need to be shifted about to align with those elsewhere for consistency.

**Comment by LeRatierBretonnien** [comment]
This will be handled in the upcoming actor sheet rework.

**Comment by ArcanistWill** [comment]
> This will be handled in the upcoming actor sheet rework.

I reviewed and it's a clean change so I just merged it before I noticed your comment! Oops, sorry it is merged already!
