### ISSUE TITLE
Existing character sheet wizard has issues with Gold generation

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#58]
**Describe the bug**
When creating a new character, if you roll their starting Gold, this is not integrated with the "new money as Items".

The rolling itself works correctly BUT there are some errors after rolling:

1. The Gold is added to the Inventory under "Heavy Items" but instead it should be added to "Money". I think when rolling Gold it's not generating the correct Item type.
2. Encumbrance is broken when adding the Gold. Each GP's weight is counted as one Stone per GP which is a huge Encumbrance and this is incorrect.
3. Additionally, the movements are all 0. I think this is due to the high Encumbrance from the Gold but we need to test after fixing the Gold.

**Related To**
#47 

**To Reproduce**
1. Go to the Actors tabe
4. Click on Create Actor
5. Click on the Dice icon over the attributes
6. Click on the Dice icons to roll the attributes, including the Gold
7. Save the values
8. Observe the updates on the main character sheet.

**Expected behavior**
1. Gold should be added as GP to the Money section
2. Gold should not affect Encumbrance as badly as it does

**Additional context**
Please note there are TWO ways to add Gold:
1. Preferred - select a starting Template for your character and manually assign the quantity of Gold from the Template
2. Optional Rule - roll for Gold during character creation, as per the existing character sheet method.

![gold-4](https://github.com/user-attachments/assets/9bf51546-7a7a-4bc6-bfc1-42fd302d6629)
![gold-5](https://github.com/user-attachments/assets/aa2d5719-d544-4bff-885b-2dacf45089c6)

**Screenshots**
While rolling the new values:
![gold-1](https://github.com/user-attachments/assets/94b676af-a52f-4beb-9379-10c1348dd89d)
After rolling and saving:
![gold-2](https://github.com/user-attachments/assets/ad3b33a1-1420-4185-88cf-351f07ed822b)
A view of the Inventory tab where the Gold is in the wrong place:
![gold-3](https://github.com/user-attachments/assets/f1971547-b026-4d89-9832-5bb6aca2b194)

**Comment by LeRatierBretonnien** [comment]
Fixed, gold is automatically added to the proper "Gold" item on a new character.
Movement is fixed also, but encumbrance of compendiums object must be reworked.

**Comment by ArcanistWill** [comment]
I tested this last Sunday and it is fixed. Thank you!
I will log a new issue with our test findings.
Closing this issue.
