### ISSUE TITLE
Regression: Clicking a spell name yields error

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#6]
**Description**
When clicking a character's Spell name in the listing, an error is produced.

**To Reproduce**
1. Create a basic character and add at least 1 Spell from Compendium
2. go to the sheet for Spells
3. Click on the Spell's name and you will see the error.
4. There seem to be 2 errors that may occur.

**Expected behavior**
The expected behavior is that when you click the spell name, the spell description will expand and be displayed in the character sheet.

**Screenshots**
Here is an example of the error that I got in the console. This was just re-confirmed with latest build.

![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/4868e16f-3940-434e-b1e3-c01548c0531b)
The below one, I think this was an error on my part. I am leaving it here just in case it is useful.
![spell-click-name-error](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/23c389a3-c62a-488b-a526-d66f33818d8f)

**Comment by LeRatierBretonnien** [comment]
Has been fixed by commit e0ce600

**Comment by ArcanistWill** [comment]
I am testing latest build with all recent fixes (12.0.15) and confirm this can be closed.
