### ISSUE TITLE
Findings from testing Combat / Combat Tracker

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#61]
**Bugs**

1. When clicking the button to go to next round of combat, I had this error:
```
ActiveEffect "rcEfVptCOt6MNweO" does not exist!
fetch @ foundry.js:72076
_remove @ foundry.js:72060
(anonymous) @ foundry.js:72079
setTimeout
fetch @ foundry.js:72079
notify @ foundry.js:71972
info @ foundry.js:71985
nextTurn @ combat.js:174
_onCombatControl @ foundry.js:90409
(anonymous) @ foundry.js:90346
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2Understand this error
```

**Other Issues, not bugs**

1. When rolling initiative for each round, after sorting the list, change the selected creature: Select the first/top creature in the initiative order. The incorrect behavior is that whichever creature was the top one BEFORE rolling is still selected after rolling. For example, a creature that is 5 creatures down the list was selected.

2. All the players observed that the new combat quick-actions can be very small tiny text unless you are very zoomed in. 
    However, Archon says it's not an issue. Still, I am curious if there is an easy solution to that problem of having all the combat icons become tiny when you are zoomed out. It's kind of a pain to have to zoom in so far. Is there an easy way to restrict it to a minimum zoom level so it doesn't get so small?
   Screenshot of what I would consider is on the border of being "too small" - see New Weapon small action button. Not sure if easy fix to restrict getting too small.
   ![too-small-token-popup](https://github.com/user-attachments/assets/ffed228e-b681-4c28-9e0b-cc90ef416631)

4. If you click the dice icon to hide the Attribute rolls, the state of being hidden is not remembered and the next time you open that popup the Attributes are visible again. Not sure what the best solution is here.

**Minor Changes**

1. Better default colors for Friendly/Hostile in combat tracker: The red text on black background is very hard to read. We need to choose better default colors for the Friendly and Hostile to something that is easier to see. 

I might do this one. I haven't looked but seems trivial. We need to test several combinations which is why it might be better for me to play with it until we're happy with it.

We tried these below and it's "close" but not quite right. The blue is nice. The red is too dim.
Friendly: blue - 175 194 238
Hostile: red - 235 114 114

**Comment by LeRatierBretonnien** [comment]
Bug 1 - Unable to reproduce, I need more context. Moroever, this is weird, because the line indicated by the error has nothing to do with my current code. Are you using a different version/branch ?

Issue 1 - Fixed
Issue 2 - The display style will be a bit bigger
![image](https://github.com/user-attachments/assets/6c052007-45c8-4ec6-a577-eee343e5cf1b)
Issue 3 - Managed

Minor 1 : This is in fact not at all default, this is values I used during my tests. I put your values as default ones.

**Comment by ArcanistWill** [comment]
> Bug 1 - Unable to reproduce, I need more context. Moroever, this is weird, because the line indicated by the error has nothing to do with my current code. Are you using a different version/branch ?
> 
> Issue 1 - Fixed Issue 2 - The display style will be a bit bigger ![image](https://private-user-images.githubusercontent.com/1085008/375971823-6c052007-45c8-4ec6-a577-eee343e5cf1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NTIwMDEsIm5iZiI6MTcyODc1MTcwMSwicGF0aCI6Ii8xMDg1MDA4LzM3NTk3MTgyMy02YzA1MjAwNy00NWM4LTRlYzYtYTU3Ny1lZWUzNDNlNWNmMWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMTY0ODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUxMmQ0MjlkYmY2OTRjN2YwYTg4N2U4MzYyOTFiYjY1NjczMGQ3ODM1ZjA1ODllNzQ4ZDc3NDg3NjJhZGE1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DGR5yOUhGk-EE2KaUaNNxHwTQPBgC4ENnB5l13yJTRc) Issue 3 - Managed
> 
> Minor 1 : This is in fact not at all default, this is values I used during my tests. I put your values as default ones.

Bug 1 - this was from the code running in your server. I was logged in as GM_1.

I agree it's an odd error I have never seen before. I will close this and file a new bug if it happens again.

Thanks for making the other changes!
