### ISSUE TITLE
Other Findings from recent testing

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#62]
**Issues and other notes, not bugs**

1. This is a high priority to look into, but it's not a bug: Can you remove the colorful image backgrounds shown in each compendium pack in the list? They do not match the game at all.
   I think this might have happened as part of the update to later Foundry and it might be a default behavior. I'm not sure. Possibly new scope or is it an error?

For example some background images have guns and lasers shown in the picture. For ACKS we would prefer a simple presentation like the older ACKS Foundry module had. Maybe later we might design a better coordinate theme of icons for it.

3. Under the Prototype Token's section for Vision Mode, we should updated it to put the ACKS vision mode in. This is new scope. We'll need to give a reference of what's needed.

**Comment by LeRatierBretonnien** [comment]
Vision mode -> open a separate ticket for this, I will wait the tickets to handle it.
Point 1 has been fixed, so I think you can close this one.

**Comment by ArcanistWill** [comment]
Thank you for making the update!

I will close this issue and file a new-work issue for the feature request so you can bid it.
