### ISSUE TITLE
Findings from testing Gold and Money feature

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#64]
**Observations - not an error**
1. Money on character sheet still allows use of the "+" button to manually add Money items, but I think that is OK because it allows adding non-standard money during a campaign. I do not think it's necessary to delete the "+" action.

**Fix to Encumbrance for money**
- [x] The character's coins that they are **carrying** should be included in their Encumbrance.
   The total number of coins from all coin types marked as being carried should be totaled together.

   - Units of every 166 coins counts as 1 item (1/6 of a stone)
   - Units of every 1000 coins is 1 stone (6 items)
   - Modulo-1000 to get number of stone, Divide remainder by 166 and round up to get number of items.

- [x] Add 2 separate counts of each money being tracked: The first is for coins being carried on character, the second is for money stored in the bank. The first counts for Encumbrance. The second does not.

```
 coin       carried     banked
   pp         100         450
   gp         250        2000
   ep           0           0
   sp        1250         175
   cp           0           0
```

**Bugs**
- [x] The display order used for the Money on the character sheet inventory is not in logical order. It should be displayed either in most-valuable to least-valuable, or else in the opposite.
Currently **Incorrect** display is out of order as:
   - Platinum
   - Electrum
   - Copper
   - Gold
   - Silver

   The desired order is:

   - Platinum
   - Gold
   - Electrum
   - Silver
   - Copper

- [x] Change the label for the money units from **GC** to **gp** - short for "gold pieces". The text **GC** is used in a few places and that is incorrect.

**Issues**

- [x] For all money values, can we make the field read-only (except for the GM or assitant GM role) for the field "Value (in Copper Coin)" - we want only the GM to be able to change the Value for money definitions.

- [x] For the Money columns displayed on character inventory, with no decimals, there are rounding confusion and we think it would be better to have decimal points shown.
- [x] Change the column's total Value (gp) to include 1 decimal point.
- [x] Change the displayed gp total for the Copper money (cp) to show 2 decimal points, and the others (I think) 1 decimal point.
   See how that looks

**Potential Change**
- [x] Is it possible to reverse the "payment order" so that the money is deducted from the smallest-denomination (least valuable) coins first, and allows keeping the most valuable coins when possible?

**Comment by LeRatierBretonnien** [comment]
All fix implemented.
I do not exactly what means this : *Is it possible to reverse the "payment order" so that the money is deducted from the smallest-denomination (least valuable) coins first, and allows keeping the most valuable coins when possible?* 
as there is no automated payment system in the game. Need precision on this.

**Comment by ArcanistWill** [comment]
> All fix implemented. I do not exactly what means this : _Is it possible to reverse the "payment order" so that the money is deducted from the smallest-denomination (least valuable) coins first, and allows keeping the most valuable coins when possible?_ as there is no automated payment system in the game. Need precision on this.

Agreed, I didn't explain it well. Here is a better description.

If I have henchmen assigned, and I use the Pay Wages button, this looks as if it correctly takes the funding from the inventory.
We are asking if it is possible to change the selection order of deducting the payment start with the least-valuable coins first (Copper), instead of starting with Platinum?

Here is an example before & after:
1. Starting out, we have 10 gp of value in each coin type.
   ![image](https://github.com/user-attachments/assets/c55aba0b-6adc-4069-9beb-f740ff7e416d)
2. Here is the Henchman sheet showing the10 gp of wages
   ![image](https://github.com/user-attachments/assets/88c7f3e3-2a14-4e89-99e6-09d2bd1bf7c1)
4. Click Pay Wages once - Here is the resulting inventory left. (Removed Platinum)
   ![image](https://github.com/user-attachments/assets/62db79c8-fd82-4087-8ee9-01977f444884)
5. Click Pay Wages twice - Here is the resulting inventory left. (Removed Gold)
   ![image](https://github.com/user-attachments/assets/b517f8a0-280f-487a-a74c-2cb8d800c1aa)

**Comment by LeRatierBretonnien** [comment]
OK, understood, fixed

**Comment by ArcanistWill** [comment]
I have re-tested the issues listed earlier here.

By adding the new headers to the table, they are now in different sizes and alignment. Can you make all the same size?
![image](https://github.com/user-attachments/assets/4898d38d-414a-4eb0-8e4f-af222673dd8e)

There is still a few areas to update - this should read **gp**, not **GC**

![image](https://github.com/user-attachments/assets/c855737c-22a4-4bde-a828-f5313b63bc7f)
![image](https://github.com/user-attachments/assets/9a500962-ad70-479b-ad1b-d4328211bb98)

**Comment by LeRatierBretonnien** [comment]
gp + alignement -> done

**Comment by ArcanistWill** [comment]
> OK, understood, fixed

I'm testing this and it is still removing the money in the opposite order, it is starting from Platinum first, then Gold, then Electrum, etc. I'm not seeing any difference.

**Comment by ArcanistWill** [comment]
> You asked for this order (cf above) : ![image](https://private-user-images.githubusercontent.com/1085008/389184932-cc6be6fd-0cd3-41ef-a9e9-6c1e694caa76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODg3MjksIm5iZiI6MTczMjM4ODQyOSwicGF0aCI6Ii8xMDg1MDA4LzM4OTE4NDkzMi1jYzZiZTZmZC0wY2QzLTQxZWYtYTllOS02YzFlNjk0Y2FhNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTkwMDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTFkMGQxMzBkODIwZGY3N2RlN2E0Y2I1MDBmMDkzMzJhOWUxYTA0MzE4ZDY0ZDljNjlkODlhZTJmOTU1MjNlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aO91JFrdogogjK1ozZScYHWrsKoDzyOWj_TuBKv_0xA)
> 
> And the order is correct : ![image](https://private-user-images.githubusercontent.com/1085008/389184955-4b442ecc-5e44-4597-a057-75777db3230e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODg3MjksIm5iZiI6MTczMjM4ODQyOSwicGF0aCI6Ii8xMDg1MDA4LzM4OTE4NDk1NS00YjQ0MmVjYy01ZTQ0LTQ1OTctYTA1Ny03NTc3N2RiMzIzMGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTkwMDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZjMjNmZmI2M2NhYmViOWM0MTM2M2QwY2M5NzAzNzk4ZWE1YjgwMGUyM2VmMjBlOGQzZjQ3Y2UwYTRjZTNlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._hRnaxWzDyQNHxr_BPaI9JXoKsqUu2gCIZ0J9vpm4nw)

Yes, the desired **display** order is correct in the character sheet. Let me try to clarify what was asked.

When using the Pay Wages button, when the code **removes** the money - is it possible to start removing from the lowest-value of coins first? That is a change to reverse the order - take away from Copper first if it has enough, then check Silver, then check Gold, etc.

For example if the Wages due is 10 gp, and I have 10 gp of Gold coins but also 10gp of Copper coins, pay the 10gp using the copper coins first, not from gold. If that seems too complex let us know. It's not 100% mandatory, just a request. But that was the intent of the question.

**Comment by LeRatierBretonnien** [comment]
OK, fixed

**Comment by ArcanistWill** [comment]
Tested and working well. Thank you! Closing.
