### ISSUE TITLE
Update Henchmen feature

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#66]
**Modification**
Please change the character sheet's tab for Henchmen so it has a new label, and you may also update comments as desired - the proper name should be changed from "Henchmen" to "Hirelings"

A Hireling can be:
- Henchman - one person
- Specialist - one person
- Mercenary - one or more

**New Functionality**
Please add the ability to specify a Quantity of the Hirelings.
For example, having a quantity of 10 Heavy Cavalry as mercenaries. This will give the ability to show hiring a group of soldiers or other support staff.

Here are the main points:
- Add a Quantity column as a numeric field
- Allow it to be empty (blank) if possible.
- If the Quantity is empty, treat it as if it is Quantity of 1 for calculating total Wages.
- If the Quantity is not empty, then calculate the total Wages for that row as (Quantity * Wage)

And a screenshot mockup:

![image](https://github.com/user-attachments/assets/237f6ebf-c2f7-4a36-a286-c62f1797c831)

**Comment by LeRatierBretonnien** [comment]
Not feasible for group numbers, see my explanation in Discord

**Comment by LeRatierBretonnien** [comment]
Updated : 
![image](https://github.com/user-attachments/assets/45716a20-f70f-4831-9197-2a0110003b95)

![image](https://github.com/user-attachments/assets/58f136c7-6b73-45d5-82aa-eb7bf6874272)

**Comment by ArcanistWill** [comment]
This looks good. Closing
