### ISSUE TITLE
ACKS Compendium Graphical Updates

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#67]
**Describe the bug**
The ACKS compendiums have bad images. See screenshot.

Many of them have the same image, and some others are different. None of them match the genre and books from ACKS. We need to replace the images.

I think that we have nice images in the rulebook that we can use as replacements.

Questions: 
1 - Is it possible to replace with better images of our own?
2 - What is the preferred image size and aspect ratio?
3 - Is it possible to reposition the title of the label in the header, or change the text font and style?

**Screenshots**
Here is an image of the problems:
![image](https://github.com/user-attachments/assets/f2622db2-e418-4bea-8e7b-a5fb432ac3d2)

**Additional context**
See attached file(s) for better images. - TODO

**Comment by LeRatierBretonnien** [comment]
The background images has been removed in the latest version available at https://jdr4.lahiette.com

**Comment by ArcanistWill** [comment]
Fixed. Closing.
