### ISSUE TITLE
Test Feedback - October 26 2024

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#68]
Here are some observations from testing.

This will include some things that are questions about how easy to fix the layout parts, and other things that seem to be a bug of some kind.

### **Hirelings**

- [x] The assignment / removal got broken and does not un-assign correctly:

1. I opened the character sheet Tirenius Junior and went to Hireling tab - it shows that Avaro is assigned,
2. I opened Avaro sheet - the Employer field is empty (I expected it to show whoever is current employer)
3. To fix this, I thought OK I will un-assign him
4. Click the delete icon from Tirenius Junior's Hirelins list, and Avaro is removed from list.
5. Drag Avaro sheet back on top of Tirenius Junior, and I got an error that he is already assigned to someone - but it does not show who.
   a. Seems to be a bug in the removal that it did not update the Hireling's state correctly
   b. Does this mean in worst-case, we need a "clear" button inside the Hireling sheet so that if an error, the DM can at least reset back to defaults?
   c. If a Hireling is already assigned, it would be "nice" to show the name of current employer
6. As a DM, how do I reset the state of Avaro now? Can you modify the code so that if I Disable "Hireling" flag, it will reset the internal state correctly so he can be re-assigned again?

**Second test of Hirelings**
1. Drag a different character Actor 01 onto Tirenius hireling list
2. This worked to assign it correctly!
- [x] 3. Cleanup - the prompt appears as expected. Do you mind making a few updates?
![image](https://github.com/user-attachments/assets/8ef2a478-7db7-4b38-a2cb-8345ccaa36d4)
   Change dialog title to include the question mark '?'
   Change dialog title to shorter "Assign {actor} as a Hireling of {employer}?" 
   Change description to say Hireling instead of Henchman - "It will enable Hireling flag in the actor, as well as..." etc.

### **Character Sheet Cleanup / Hireling Cleanup**

The bad text is a known legacy problem but it is getting worse as more fields are added.

I will give a list below.

These first items I would really like to see updated:
- [x] * For Henchmen, The label "Fate points" wraps and extends up above the edit line. Can you abbreviate Points to Pts (capitalize the P) and add non-breaking space - "Fate&nbsp;Pts" ?? This might make 1 line, not 2? Or just "Fate Pts" if it can't take a non-breaking space.
- [x] * The order of the Hireling list needs to be alphabetical "Henchman, Mercenary, Specialist" in that order. The default setting would then be Hireling not Mercenary.
- [x] * Line 2: The display order needs to be revised. Can we have the first fields in Line 2 be exactly the same for either PC or Hireling? This will move the unique data for Hirelings into 1 place.
- [x] Line 2 for Player Characters:
   * Alignment
   * Age
   * Fate Pts
   * Title (instead of Henchman data, this can be a longer field that takes up the same space)
- [x] Line 2 for Hirelings:
   * Alignment
   * Age
   * Fate Pts
   * (The rest are for a Hireling and replaces Title)
   * Wage
   * Morale
   * Loyalty
   * Employer 
   * Type (Henchman/Mercenary etc)

These fixes are sizing and alignment related. It's just so ugly and it would be really nice to improve it:
* Alignment
- [x]    * Can you make all these fields Left-Aligned? It would look SO MUCH better if the entry text was on the left.
- [x]    * Can you make the editable part of the field line up vertically with the label part? I will draw a line.
   * Make items from 1 row down to the next row, line up as well
- [x] * The number fields should all be set to be the same size. They all contain numbers of 1 to 4 digits. They are probably too long.
   Wage,
   Age,
   Fate Points,
   Morale,
   Loyalty - this one obviously a lot longer than the others
- [x] * Line 3:
   *  The Class could be longer
   * The Level could be shorter (it's only max 2 digits)
   * The Experience and Next Level might be too long, But main thing check that the 2 of them use the same size.

Here's a screenshot:
![image](https://github.com/user-attachments/assets/af7d2141-fd80-43a7-bbfb-03de1ab357d4)

Example of how large the number fields are - they don't need to be so big, it would be nice if they were more consistent.
![image](https://github.com/user-attachments/assets/41b3405d-fea6-44cc-b0e9-ca78d48f83b6)

**Comment by LeRatierBretonnien** [comment]
*Character Sheet Cleanup / Hireling Cleanup section* -> All fixes done;

**Comment by LeRatierBretonnien** [comment]
All issues fixed and available at the test server

**Comment by ArcanistWill** [comment]
Here is an interesting corner-case:

If I use the Tweaks menu to disable the Henchman flag, the child sheet does update, but it does not propagate up to the employer. The henchman needs to be removed from the employer sheet also.

If I just simply drag the same guy over the employer again, it asks me (correctly) if I want to make them a Hireling.

If I say Yes, then I get an error Henchman already added to another actor.

The workaround is that you can press Delete on the employer sheet and remove the henchman, then drag him over again.

**Comment by LeRatierBretonnien** [comment]
Ah yes, corner case. Propagation of the deletion is done.

**Comment by ArcanistWill** [comment]
Everything has been updated and fixed, thank you! Closing.
