### ISSUE TITLE
More Character Sheet Cleanup

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#69]
Here is a list of character sheet problems that make it very ugly.
I'm not sure how easy it is to fix this.
I think we really need a better layout manager. Maybe a simple grid layout that is resizable, would be better. Everything is a mess.

Here are some 10 or 12 problems. How many can be easily fixed before next release?

![image](https://github.com/user-attachments/assets/1b43c5e1-e0ef-49f7-8c9c-372f79019d80)

- [x] 1, Change the Favorites to use the same style as the other boxes (a black inverted rectangle, etc)
- [x] 2. Everyone says "it's too big" - the character sheet takes up too much space in the game and covers too much. This is from the bad layout and all the wasted space. See item 10 also.
   * Fix - how do we make it less wide? That would help a lot. Can we move a field or 2 from below, up into the empty space by marker 10 above.
- [x] 3. Why does sometimes a field have an underscore / line in it, and other times not? Look at HD compared to Init compared to Mortal Wounds.
- [x] 4. The data for the movement speeds is shown next to the labels, but the data for the proficiencies is under them, and there is a lot of wasted space.
   * Can we make them consistent between the 2 kinds of data? Would it be better to have proficiency labels side by side and not above/below? 
   * Can we pack the proficiencies fields into the same container as the movement so it doesn't have all that wasted space?
   * Can we align them better? This is a general comment.
- [x] 5. Why is HD/Init/Surprise lower than Paralysis etc.
- [x] 6. Can we have a lined border around the Favorites area?
- [x] 7. Going across left to right, nothing is aligned and it's so ugly.
- [x] 8. Is it possible to make the Labels inside the attributes aligned with the data values of the attributes (WIL aligns with the number 9, etc)
- [x] 9. The same visual alignment problem here but it's even uglier. Like, I don't know why Cleaves and Throw aren't using the same alignment at least. If we could make them all 1 line labels, and have all the numbers aligned, that would help a lot. Could say "Heal Rate" and "Mort Wds" or something maybe.
- [x] 10. I am just pointing out all the empty space. Lots of vertical and horizontal space.
   * Is there too much horizontal padding sometimes?
   * Is the movement bar too wide?
  
This is for the second image, just one observation as of now:

![image](https://github.com/user-attachments/assets/eb4f9c52-2ca4-4558-96b4-712ca5cbc780)

- [x] 20. Can you center-vertical-align Total Wages and Available Money so it is on-center with the same line as the Pay button? Or make the Pay button shorter so that everything is aligned?

**Comment by ArcanistWill** [comment]
Almost ready to close. What did you decide for item 20 about the alignment? Is it too much work or is it possible? Thanks!

**Comment by AP-Sig** [comment]
> Here is a list of character sheet problems that make it very ugly. I'm not sure how easy it is to fix this. I think we really need a better layout manager. Maybe a simple grid layout that is resizable, would be better. Everything is a mess.
> 
> Here are some 10 or 12 problems. How many can be easily fixed before next release?
> 
> ![image](https://private-user-images.githubusercontent.com/153968937/380446297-1b43c5e1-e0ef-49f7-8c9c-372f79019d80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NjY0MzgsIm5iZiI6MTczMjY2NjEzOCwicGF0aCI6Ii8xNTM5Njg5MzcvMzgwNDQ2Mjk3LTFiNDNjNWUxLWUwZWYtNDlmNy04YzljLTM3MmY3OTAxOWQ4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMDA4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDcxY2NmN2Q4YmZlMzYzZThhYjI4MzZkYjk2ZGNhYTgyNjBkOGViNGU0NGQ2YTg2OGM5YjY1M2JmODdkMDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X13Po1gRAG140qCN8dwlTMKJl60mkruQxfJt99X_JoQ)
> 
> * [x]  1, Change the Favorites to use the same style as the other boxes (a black inverted rectangle, etc)

The Favorites window has the same styling as the rest of the boxes.

> * [x]  2. Everyone says "it's too big" - the character sheet takes up too much space in the game and covers too much. This is from the bad layout and all the wasted space. See item 10 also.
>   
>   * Fix - how do we make it less wide? That would help a lot. Can we move a field or 2 from below, up into the empty space by marker 10 above.

I don't think it's less wide to me, but the layout looks good.

> * [x]  3. Why does sometimes a field have an underscore / line in it, and other times not? Look at HD compared to Init compared to Mortal Wounds.

Underscores/lines are still present, but it's fine visually for now.

> * [x]  4. The data for the movement speeds is shown next to the labels, but the data for the proficiencies is under them, and there is a lot of wasted space.
>   
>   * Can we make them consistent between the 2 kinds of data? Would it be better to have proficiency labels side by side and not above/below?
>   * Can we pack the proficiencies fields into the same container as the movement so it doesn't have all that wasted space?
>   * Can we align them better? This is a general comment.

Alignment and space usage looks fine for now.

> * [x]  5. Why is HD/Init/Surprise lower than Paralysis etc.

Changes look fine.

> * [x]  6. Can we have a lined border around the Favorites area?

I'm seeing a border around this area.

> * [x]  7. Going across left to right, nothing is aligned and it's so ugly.

Alignment changes look good for now, unless the window width is decreased. At default width everything is OK.

> * [x]  8. Is it possible to make the Labels inside the attributes aligned with the data values of the attributes (WIL aligns with the number 9, etc)

These values appear to be aligned.

> * [x]  9. The same visual alignment problem here but it's even uglier. Like, I don't know why Cleaves and Throw aren't using the same alignment at least. If we could make them all 1 line labels, and have all the numbers aligned, that would help a lot. Could say "Heal Rate" and "Mort Wds" or something maybe.

These alignment issues appear to be fixed.

> * [x]  10. I am just pointing out all the empty space. Lots of vertical and horizontal space.
>   
>   * Is there too much horizontal padding sometimes?
>   * Is the movement bar too wide?

This looks fine for this release. It's probably the widest element, and doesn't resize with the window but it's functional and doesn't overlap if the window isn't too narrow.

> 
> This is for the second image, just one observation as of now:
> 
> ![image](https://private-user-images.githubusercontent.com/153968937/380447386-eb4f9c52-2ca4-4558-96b4-712ca5cbc780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NjY0MzgsIm5iZiI6MTczMjY2NjEzOCwicGF0aCI6Ii8xNTM5Njg5MzcvMzgwNDQ3Mzg2LWViNGY5YzUyLTJjYTQtNDU1OC05NmI0LTcxMmNhNWNiYzc4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMDA4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGEwYWQ5MjE3NjcxOWYwZGNjZmJlMjEyYzRiNTAzZGQ0YTAzODBhMDJiODdhNWIxOWRmNjIzNTYwN2YyNmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.686FPwzJUD13ScyYjQXzRfEQm-pF_svINY-ok_X7gpU)
> 
> * [ ]  20. Can you center-vertical-align Total Wages and Available Money so it is on-center with the same line as the Pay button? Or make the Pay button shorter so that everything is aligned?

Alignment here looks just fine for now.

Overall, I didn't see any unexpected behavior in actor creation, movement, rolling, etc. I'm not seeing any bugs with adding armor and AC not calculating on equip, which is something I was seeing in the previous version.

Like OmenOwl noted, there's no longer a dropdown for Languages but that's the only thing I've seen missing from a UI perspective.

**Comment by ArcanistWill** [comment]
Fixed! Closing.
