### ISSUE TITLE
Character Generation: Dice Roller too narrow

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#7]
**Describe the bug**
Truncates the title which makes it look bad. See screenshot.
Not sure of best solution.

- Make the dialog wider?
- Shorten the title?
- What happens if character name is really wide? Do we need to show character name at all?

**To Reproduce**
1. Add an Actor
2. Click on the attribute roller

**Screenshots**
![char-create-1](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/21e91cb5-5aba-4516-963f-26adddb32163)

**Comment by LeRatierBretonnien** [comment]
Up to you. Easiest solution : remove the name and only display "Character generator"

**Comment by ArcanistWill** [comment]
> Up to you. Easiest solution : remove the name and only display "Character generator"

Don't worry about this one.
I'll think about it and either leave it as is, or else I can shorten the text displayed:

![image](https://github.com/user-attachments/assets/0fed4c60-b4c1-4a17-a1ff-fd51788e563c)

**Comment by ArcanistWill** [comment]
@LeRatierBretonnien I pushed this little commit to the character-sheet branch. It affects 2 of the language translation files.

It's not an important change but I decided to update and close this. Why leave it open?
