### ISSUE TITLE
Character Sheet - Add/Remove Languages is broken

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#70]
**Describe the bug**
A user just reported this and I have reproduced it with several different failure modes.

This is not super high priority, but it would be nice to fix it on master and then issue a bug-fix release (before releasing all the changes that are in-process for the character sheet)?

I do not see any errors in the Console when trying to add or remove languages from an existing character in our game session, but nothing happens.

**To Reproduce**
Failure Adding(1):
This is for the ongoing game session I'm in, we started with Foundry v 0.9 when setting up the character sheets. It's running a slightly older build. The Languages list does show the "+" sign but it does not work.

* Open a character sheet in Archon's game on Forge site
* Go to the Notes tab
* In the Languages area, choose "+" to display a dialog where you can select a new language.
* Select a language from the list.
* Choose OK
* The dialog closes but the language is not added to the list.
* fail

Failure Adding (2):
This is for the game session in your test server - Languages here has **no** "+" sign and I can't add anything.

* Open a character sheet in test server
* Go to the Notes tab
* In the Languages area, there is no "+" button - cannot display a dialog where you can select a new language.
* fail

Failure Removing Language:
* If there is a language listed, click the icon to delete it
* The language is not removed
* fail

**Screenshots**
![image](https://github.com/user-attachments/assets/eb0c0c1c-fde5-4346-8180-1d6e81761e82)

**Comment by LeRatierBretonnien** [comment]
In the new actor branch, languages are item, so the point (2) above is invalid.
In the new branch : 
1 - Create a language item
2 - Drag&drop it onto the character sheet
3 - The language is displayed
4 - Press   the delete icon to remove it

**Comment by ArcanistWill** [comment]
> In the new actor branch, languages are item, so the point (2) above is invalid. In the new branch : 1 - Create a language item 2 - Drag&drop it onto the character sheet 3 - The language is displayed 4 - Press the delete icon to remove it

There is a little bit more to coordinate for this then. I see that when creating a new language, now I can specify an icon for it.
![image](https://github.com/user-attachments/assets/c9e59941-ed81-47ca-a14c-ea800ea24467)

**Comment by LeRatierBretonnien** [comment]
Yes,  The language compendium is created on my side, with a default picture. I will push it in a few minutes

**Comment by ArcanistWill** [comment]
Fixed. Closing.
