### ISSUE TITLE
Implements Saves do not carry over values for wand saves

### ISSUE THREAD

**Issue by wyatt-kinkade** [AutarchLLC/foundryvtt-acks-core#71]
**Describe the bug**
When updating to the new version 

**To Reproduce**
1. Update to new code
2. Open existing sheet
3. Look at Implements Save on an Actor

**Expected behavior**
See the previously configured implements save

**Screenshots**
![image](https://github.com/user-attachments/assets/d73e171b-2fe7-4497-8930-4d71ea2f6f66)

![image](https://github.com/user-attachments/assets/cf1bdad6-ae09-4e78-8178-571021c7e0a9)

**Additional context**
It looks like the implements variable value needs to be made to match existing wand saving throw variable numbers somehow or the wands variable should be called upon by the sheet. I imagine there's a preferred option by the maintainer, so I will not attempt to resolve this and enter a PR.

**Comment by LeRatierBretonnien** [comment]
Seems working in my local branch, so maybve an update issue. New update of this branch will be pushed tonight, so you will be able to test again.

**Comment by wyatt-kinkade** [comment]
Updated to new code, I have a hotfix ready for session but I still see the same situation.

**Comment by LeRatierBretonnien** [comment]
Is it happening on an old character or a new one ? Also all characters have this or only one ?

**Comment by wyatt-kinkade** [comment]
All pre-existing characters, the forms and everything can be filled out for the new variable, but I imagine the intent was for a smooth transition from the wands variable to the implements variable.

**Comment by LeRatierBretonnien** [comment]
OK, so this is because you did not change the system version when applying the migration. If the system version is updated BEFORE applying the new release, then the field will be automatically updated. If you keep an old or wrong system release, then the migration does not occur, and you see this kind of result.

So this can happen for people applying the branch onto the legacy version during beta phase, but it will not happen during the official update of the release.

**Comment by ArcanistWill** [comment]
> OK, so this is because you did not change the system version when applying the migration. If the system version is updated BEFORE applying the new release, then the field will be automatically updated. If you keep an old or wrong system release, then the migration does not occur, and you see this kind of result.
> 
> So this can happen for people applying the branch onto the legacy version during beta phase, but it will not happen during the official update of the release.

@LeRatierBretonnien @wyatt-kinkade If I understand correctly, then this issue should not happen during the upgrade to the formal release.  if that's true, then I will close this and we can always re-open it. 

I think we should carefully update 1 or 2 people's worlds once we have a test release, before we make it official.

**Comment by ArcanistWill** [comment]
Closing, we think this is fixed as of 12.2.0 release. If not, will re-open.
