### ISSUE TITLE
Strange Number Glyphs

### ISSUE THREAD

**Issue by wyatt-kinkade** [AutarchLLC/foundryvtt-acks-core#72]
**Describe the bug**
On the title of Actors there are strange/missing glyphs in the font used.

**To Reproduce**
1. Type in a non-letter character in an Actor's name
2. Character is either missing a glyph or provides a glyph that is not useful

**Expected behavior**
The title font displays useful glyphs, compare in the below screenshot the name in the top left of the Actor's window and that displayed largely in the custom font in comparison.

**Screenshots**
![image](https://github.com/user-attachments/assets/c31f1030-bcdc-4705-8224-3767c3111aef)

**Additional context**
Going to defer to maintainer on how this should be fixed

**Comment by ArcanistWill** [comment]
> Unfortunately, this is the real content of the "Archeological caps" font that has been chosen for the game (see here for example : https://www.dafont.com/archeologicaps.font ). A new font must be chosen by the ACKS team.

Yes, I'll do some checking and find one that is better implemented.

**Comment by ArcanistWill** [comment]
I propose one of the following fonts. I checked and they all support the basic characters we would want including numbers.

PAY ATTENTION TO THIS WHEN DECIDING
* Check the font kerning - that is, the space between certain characters next to each other like AV. Does it look nice? Some of these just have bad spacing and it does not look good. You'll know when you see it.
* Check the overall size and width - some of these are going to be a lot wider which means it won't display as much information as a more condensed font.
(They may all look the same width if Github shrinks them to fit the window.)

1. Oranienbaum
![image](https://github.com/user-attachments/assets/85179742-6679-447f-8aab-55e330da5436)

2. Inder
![image](https://github.com/user-attachments/assets/d76001ad-3ce2-46e1-a2ea-ca7c07d3b0ba)

3. Romanesque Serif Regular
![image](https://github.com/user-attachments/assets/1d2361ed-d924-45d1-b778-c922f17d92c9)

4. VTC Switchblade
![image](https://github.com/user-attachments/assets/6d4662fd-1c85-456d-95a2-be4a3de63310)

5. Cinzel Regular
![image](https://github.com/user-attachments/assets/e365a82e-eeac-454e-ada7-cd7c49ba3b4e)

6. Weiss Initialen - Regular, or Alternate
![image](https://github.com/user-attachments/assets/0cfd2cf3-172b-4237-87af-30fed24594be)

7. Diehl Deco Regular
![image](https://github.com/user-attachments/assets/eabc6f99-0cfd-4901-bba1-e49da87cf79b)

**Comment by ArcanistWill** [comment]
We've picked this font to replace the Archeologicaps:
Oranenbaum: https://www.1001fonts.com/oranienbaum-font.html

**Comment by ArcanistWill** [comment]
Changed font and fixed the issue.
