### ISSUE TITLE
NPC Health does not calculate correctly

### ISSUE THREAD

**Issue by wyatt-kinkade** [AutarchLLC/foundryvtt-acks-core#74]
**Describe the bug**
When the dice icon next to HP on a monster token is clicked the HP only recalculates the current HP value and not the maxium HP

**To Reproduce**
1. Open a monster actor
2. Click on the dice icon next to HP

**Expected behavior**
Both the Current and Maximum HP are set to the rolled number when the dice icon in question is clicked

**Screenshots**
![image](https://github.com/user-attachments/assets/14b72e6b-1c32-4365-b3d7-1f56f13be24e)

**Comment by LeRatierBretonnien** [comment]
PR accepted
