### ISSUE TITLE
Hard-coded absolute path to root ("/") somewheres in the code

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#77]
**Describe the bug**
A user reported this back in 2022 and just upgraded, and said that it is still happening with the most recent release.

We need to look into whether there is a hard-coded path relative to the server's root like "/something" and see if we can change to relative path.

Apparently resources and colors don't load right. See screenshot below.

**Prior History in Discord log from 2022**

- [4:11 AM]Piisami: Has anyone else had an issue with the foundry sheets? Mine are currently bugging, the dark parts like 'HP' are light and the tabs like inventory and others are transparent. System reinstall did not help.
- [4:11 AM]Piisami: I have the issue on a dedicated server but if I run it on the client it's not there.
- [6:20 AM]Piisami: My computer-literate friend who set up the server took a look at it, it seems it's because of the use of 'url("/' in acks.css, the server he set up has an additional /XXX/system/etc which then breaks
- [6:22 AM]Piisami: "Trying to pull resources from root, even when routePrefix is set on foundry options" is what he said to say is the problem. Some of those words I understand.
- [7:24 AM]Ka: I am not having these issues you mentioned, but other ones like the button for rolling stats on character sheets not working.
- [9:09 PM]Piisami: Those, as well as everything else on it, work perfectly for me. Only the sheets have a problem.
- [9:39 PM]The Happy Anarchist: I can confirm the sheet problem for a few of the clickables, they were missed in the coversion to v9.
- [9:39 PM]The Happy Anarchist: Not a huge priority since you can always just /r in the chat
- [9:40 PM]The Happy Anarchist: A bigger problem is now we need to convert from v9 to v10, ugh.
- [11:59 PM]Piisami: It's also in config.js, lines 96-104. Those call direct from the root. If I knew how to code I would fix this.
- [8:22 AM]Piisami: My friend fixed it by brutely replacing 'url("/systems/' and similar instances with 'url("/XXX/systems/' in acks.css and adding it in config.js as well. It may be the 'url' command/operator or whatever it's called would need to be replaced for a more elegant solution. For whatever reason it still keeps pulling gold.png and claw-hammer.webp from root but those are livable as the sheets are fixed. 
- [9:15 AM]Piisami: Acks-monsters.db, item images fail to load if the server is not at root because of "img":"/systems...", works fine with "img":"systems..."

**2024 - Today - Screenshot of character sheet**
![image](https://github.com/user-attachments/assets/8b4198b0-5caa-4689-8029-3da5c1cf63f2)

**2024 - Today - Discord log**
- [2:36 PM]Piisami: /systems/acks/assets/
- [2:37 PM]Piisami: It has to do with that one, needs adding the non-root path before
- [2:37 PM]Piisami: So it says /EXAMPLE/systems/acks/assets/back.png instead
- [2:38 PM]Piisami: And /ui/parchment.jpg . We tracked it by opening up the source code and I looked at what was wonky and tried looking at the error page of the browser, he worked magic. Bloody wizards.
- [2:40 PM]Piisami: It should call dynamically (is that the correct word?) instead of from the fixed address of /systems/acks/assets/, /ui/ and /icons/svg/ which points to root.
- [2:46 PM]Piisami: /systems/acks/acks.css and systems/acks/module/config.js urls need to be prefixed with routePrefix. He used sed replace.
![image](https://github.com/user-attachments/assets/fb6796c8-0028-4a41-bef1-9c077cf14385)

- [2:47 PM]Piisami:
![image](https://github.com/user-attachments/assets/ea23f382-d65b-4ee4-966b-f4cba1c8047b)

- [2:49 PM]Piisami: The latter image fixes another error in the tag-images, you can contact the dude I pinged if you need further details. He said he can explain it in more detail if needed
![image](https://github.com/user-attachments/assets/f7d31de7-b950-4c90-91d1-832d02d9c363)

**Comment by LeRatierBretonnien** [comment]
I don't understand the issue. It seems the user has changed the path himself, with an editor.

**Comment by ArcanistWill** [comment]
> I don't understand the issue. It seems the user has changed the path himself, with an editor. This user has a strange and weird install. The data path of the system is following the FoundryVTT requirements, as in all other systems, so from my point of view, this is NOT an issue of the system. The user is doing something wrong in his install and must fix it.

I don't know what they are doing either. But it seems like it's a good question - why are these paths absolute paths to the URL? Normally I would not start a URL with `"/"`? Should they start with `"./systems/acks/assets/"` or `"systems/acks/assets/"`? Can it still work if we change it to a relative path to server root?

```
in config.js
  tag_images: {
    melee: "/systems/acks/assets/melee.png",
    missile: "/systems/acks/assets/missile.png",
    slow: "/systems/acks/assets/slow.png",
    twohanded: "/systems/acks/assets/twohanded.png",
    blunt: "/systems/acks/assets/blunt.png",
    brace: "/systems/acks/assets/brace.png",
    splash: "/systems/acks/assets/splash.png",
    reload: "/systems/acks/assets/reload.png",
    charge: "/systems/acks/assets/charge.png",
  },
```

**Comment by LeRatierBretonnien** [comment]
This is correct : from the server point of view, this is the root of the Foundry filesystem. So this is correct, yes. But we can change to a relative one, yes, I suspect it comes from the first OSR system from which ACKS is derivated.

**Comment by LeRatierBretonnien** [comment]
So '/' removed, to close this.

**Comment by ArcanistWill** [comment]
> This is correct : from the server point of view, this is the root of the Foundry filesystem. So this is correct, yes. But we can change to a relative one, yes, I suspect it comes from the first OSR system from which ACKS is derivated.

Yes absolutely, a legacy problem.

There are 12 places inside acks.css plus the above places in the config.js
Thanks for updating.

**Comment by ArcanistWill** [comment]
Need to investigate these also:

```
grep systems acks.css  | grep \"/
  background: url("/systems/acks/assets/back.png");
  background: url("/systems/acks/assets/back.png");
  background: url("/systems/acks/assets/back.png");
  background: url("/systems/acks/assets/back.png");
  background: url("/systems/acks/assets/treasure.png") no-repeat center;
  background: url("/systems/acks/assets/back.png");
  background: url("/systems/acks/assets/shield.png") no-repeat center;
  background: url("/systems/acks/assets/heart_empty.png") no-repeat center;
  background: url("/systems/acks/assets/heart_full.png") no-repeat center;
  background: url("/systems/acks/assets/back.png");

and:

./module/treasure.js:    // sound: "/systems/acks/assets/coins.mp3"
./module/dialog/party-sheet.js:    const template = "/systems/acks/templates/apps/party-select.html";
./module/dialog/character-creation.js:    const content = await renderTemplate("/systems/acks/templates/chat/roll-creation.html", templateData)
./module/config.js:    melee: "/systems/acks/assets/melee.png",
./module/config.js:    missile: "/systems/acks/assets/missile.png",
./module/config.js:    slow: "/systems/acks/assets/slow.png",
./module/config.js:    twohanded: "/systems/acks/assets/twohanded.png",
./module/config.js:    blunt: "/systems/acks/assets/blunt.png",
./module/config.js:    brace: "/systems/acks/assets/brace.png",
./module/config.js:    splash: "/systems/acks/assets/splash.png",
./module/config.js:    reload: "/systems/acks/assets/reload.png",
./module/config.js:    charge: "/systems/acks/assets/charge.png",
./module/item/entity.js:      let img = "/systems/acks/assets/default/item.png";
./module/item/entity.js:          img = "/systems/acks/assets/default/spell.png";
./module/item/entity.js:          img = "/systems/acks/assets/default/ability.png";
./module/item/entity.js:          img = "/systems/acks/assets/default/armor.png";
./module/item/entity.js:          img = "/systems/acks/assets/default/weapon.png";
./module/item/entity.js:          img = "/systems/acks/assets/gold.png";
./module/item/entity.js:          img = "/systems/acks/assets/language.png";
./module/actor/monster-sheet.js:        "/systems/acks/templates/actors/dialogs/monster-saves.html",
./module/actor/character-sheet.js:        "/systems/acks/templates/actors/dialogs/lang-create.html",

```

**Comment by LeRatierBretonnien** [comment]
Changes done

**Comment by ArcanistWill** [comment]
Fixed! Thank you.
