### ISSUE TITLE
Replace the font Crimson Text with EB Garamond

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#78]
**Describe the bug**
The font Crimson Text looks nice but it lacks some characters. The other font choice of EB Garamond looks almost the same but it has the missing characters. We need to update (again) to replace this font.

https://fonts.google.com/specimen/EB+Garamond

**Comment by LeRatierBretonnien** [comment]
Done

**Comment by ArcanistWill** [comment]
Thank you!
