### ISSUE TITLE
A Spell Description links to what?

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#8]
**Describe the bug**
In the chat log, a spell description has selectable links that give the impression they do something. What's this about?

I think this is a bug, not a feature enhancement, but it seems to have been present in the old code too.

**To Reproduce**
1. Create character with at least one spell: Bless
2. Click on the spell's icon so it rolls and appears in the chat log
4. Click on chat log - these look like selectable item links
5. See error

**Expected behavior**
Unclear - is this supposed to open up the corresponding item description? That would be nice. What else?

**Screenshots**
![spell-item-links-what](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/fba0806f-4053-48b2-a627-056f0b62cd1b)

**Comment by LeRatierBretonnien** [comment]
This is auto-link to items when "something" (ie actor, scene,item, rolltable ,...) is dropped onto a journal: 
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/1085008/adc3f134-cb21-4bb6-9e99-2ce8854b8450)

It allow to do easy linking between "objects" of the game. 

In this specific case, the description of "Bless" has been enhanced with a link to a "Holy Water" item from the world itself. As this "Holy Water" item does not exist in the world (neither in compendiums, it seems), the auto-link is displayed as a broken one.

**Comment by ArcanistWill** [comment]
> This is auto-link to items when "something" (ie actor, scene,item, rolltable ,...) is dropped onto a journal: ![image](https://private-user-images.githubusercontent.com/1085008/316254086-adc3f134-cb21-4bb6-9e99-2ce8854b8450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMTE2MzMsIm5iZiI6MTcxMTIxMTMzMywicGF0aCI6Ii8xMDg1MDA4LzMxNjI1NDA4Ni1hZGMzZjEzNC1jYjIxLTRiYjYtOWU5OS0yY2U4ODU0Yjg0NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMTYyODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQwODViOGQ4Y2VlZmNmMzIyZjk5OTdkNGJiMTlmYmI3YTBjNDZjM2YwMThhY2YwMmQyYjc0NTdkYzQ2MzMxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rh9VmGe6W0L-PU7INGRz7vsyAWsM0lGpceRYBkZjiqg)
> 
> It allows to do easy linking between "objects" of the game.
> 
> In this specific case, the description of "Bless" has been enhanced with a link to a "Holy Water" item from the world itself. As this "Holy Water" item does not exist in the world (neither in compendiums, it seems), the auto-link is displayed as a broken one.

I understand your explanation. However I am confused because it does exist in compendium - see image. Does this mean that the link is corrupted?

![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/153968937/abbf2736-ba72-4dbe-a479-a6b5d1024abb)

**Comment by LeRatierBretonnien** [comment]
The link is not "corrupted", it is completly wrong.
Here is the current link : 
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/1085008/9ee76fca-d1bf-433c-b364-049811a8657a)

And here is the link from the item in the compendium  : 
![image](https://github.com/AutarchLLC/foundryvtt-acks-core/assets/1085008/b344e8c8-c1be-400e-8fbc-d475ef725c7e)

Basic rule : Alaways do linking from compendiums, not items in the world.

**Comment by ArcanistWill** [comment]
I am closing this issue because all of the current spells in the compendium have to be revised to update them for ACKS II. During that process we should also fix any links to items.

There is no point keeping this open.
