### ISSUE TITLE
Test Feedback - November 23 2024

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#80]
**Notes from Character Sheet Testing**
This is a work in progress and I will add to the list during testing.

- [x] 1. The Morale and Loyalty fields have dice symbol that appears right on top of the data field when trying to edit the value. Can this be adjusted so the dice icon is to the left of the data field? In this screenshot, the value '0' is under the dice.
![image](https://github.com/user-attachments/assets/61ba882a-b69f-48fe-82bd-7f07d8c944a4)

- [x] 2. When I created a new Character, the Money list was empty. What is the desired behavior? At one time when creating a new character, all the money types were added automatically to the list.
- [ ] 3. Is it possible to fix the default sorted order of the items in the ACKS Money list so that they are listed in the same sort order (most valuable to least valuable) as on the character sheet? Instead of this:
![image](https://github.com/user-attachments/assets/49b0d4ad-9403-4c16-bd2d-bc34eb297f97)

- [ ] 4. Stealth and Climb are not set.
![image](https://github.com/user-attachments/assets/b90b60f3-4145-407a-93ea-09a0194ef024)

**Comment by LeRatierBretonnien** [comment]
For task #3, this is already the case. I suspect you have the wrong copper values inside your money items
![image](https://github.com/user-attachments/assets/e1d975f8-0a0d-43d2-9ef1-69233f7a60bb)

**Comment by ArcanistWill** [comment]
> For task #3, this is already the case. I suspect you have the wrong copper values inside your money items ![image](https://private-user-images.githubusercontent.com/1085008/389186159-e1d975f8-0a0d-43d2-9ef1-69233f7a60bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODk4NDQsIm5iZiI6MTczMjM4OTU0NCwicGF0aCI6Ii8xMDg1MDA4LzM4OTE4NjE1OS1lMWQ5NzVmOC0wYTBkLTQzZDItOWVmMS02OTIzM2Y3YTYwYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTkxOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI1OTdmYzBmNTNhMmZjYmU0MDY5OWM2ODg1YzMwMzUwNGI4MTdmYmVjZWZjZmEzMDFjYWFiYmI4MWEwYmJlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BcxPuL1QG94f4nlVqkEpvFrR2C3ht9r6pgylLouWeeA)

I am talking about the display in the sidebar compendium. It did not match the actual character sheet.
- The character sheet is correct as you show
- The compendium list is incorrect

This is what I am describing. Here's a better image for context.
![image](https://github.com/user-attachments/assets/52af4216-d052-46b5-bbc9-ddbedcddbb4c)

**Comment by LeRatierBretonnien** [comment]
OK, I can't control compendium sorting easily, so I suggest to keep it like that for now. No easy solution for that.

**Comment by ArcanistWill** [comment]
> OK, I can't control compendium sorting easily, so I suggest to keep it like that for now. No easy solution for that.

OK, I will close it and we won't fix. Thanks.
