### ISSUE TITLE
Last Updates - Dec 1 2024

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#81]
**Closing out the last updates**

- [x] 1. Please make the monster sheet have the same order of Saving Throws as the character sheet. If it is _easy_ can you also add the dice icons so that the monster sheet throws looks exactly like the character sheet?

The order of the saving throws should be:

- Paralysis
- Death
- Blast
- Implements
- Spells

for both **characters** and **monsters.**

- [x] 2. The character generator message in the Chat window is too wide with this font. Notice Intelligence, Constitution, Charisma all have a bad line wrap. Also, it looks like actually it COULD fit but the box is too small?
What do you recommend? Should it use the Abbreviations for the attributes instead of the full names? Use STR, INT, etc.  Or else make the font a little smaller?
![image](https://github.com/user-attachments/assets/fe56617b-6344-4ecf-af84-fc1e49883428)
![image](https://github.com/user-attachments/assets/cbed50de-ad71-4fa3-8d12-7092f1dfd3cd)

- [x] 3. Need a new Character Sheet "Tweak" boolean setting:
* Add a new Boolean checkbox (enable/disable) to the tweaks menu for characters.
Call it something like Auto-Calculate Movement from Encumbrance.
* Update the code to check that setting
* If the setting is Checked (On), calculate the base movement from Encumbrance as before.
* If the setting is Unchecked (Off), make the movement fields editable so the player can manually enter the movement rates.

**Comment by LeRatierBretonnien** [comment]
Task 2 above is done.

**Comment by LeRatierBretonnien** [comment]
Task 3 done also

**Comment by ArcanistWill** [comment]
Items 1 and 2 pass, thank you!

Testing item 3 (Tweaks for Calculate Movement): It's just about there but, after more testing it appears Stealth and Climb are not auto-calculated. I gave this information previously. Let me know if you need it again?

Error - Does not reset fields when Re-Enabling Calculate Movement:
1, First turn OFF the checkbox. This will allow data entry to the movement fields.
2. Manually enter 999 for every field.
3. Turn ON the checkbox
4. Observe the error that some fields are reset and others are not:
![image](https://github.com/user-attachments/assets/a62153e8-91f3-4392-8d5e-49943c59764a)

Error - Does not calculate Stealth and Climb speeds:
1. Drag many heavy items to the character until the encumbrance changes.
2. Observe that the last 2 movement rates are not calculated.
![image](https://github.com/user-attachments/assets/4051b20a-8958-4b6a-8c2a-27768c1eb70c)

**Comment by LeRatierBretonnien** [comment]
^^ Fixed!

**Comment by ArcanistWill** [comment]
Fixed all, closing!
