### ISSUE TITLE
Restore support for Polyglot languages module

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#87]
**Regression**
The recent update to add Languages as separate items, broke compatibility with Polyglot module. This used to work.

Investigate how to support and integrate this module.

See:
https://github.com/mclemente/fvtt-module-polyglot

https://foundryvtt.com/packages/polyglot/

**Comment by LeRatierBretonnien** [comment]
Polyglot support added in [f038b79](https://github.com/AutarchLLC/foundryvtt-acks-core/commit/f038b79120bff49795c3b69cd3273fa3f7f3b26a)

**Comment by ArcanistWill** [comment]
Closing
